# config.yaml
window:
  width: 1920
  height: 1080
  name: "Cellula"

playground:
  margin:
    - 20
    - 20

sim:
  speed: 2
  cell_friction: 0.05
  friction_ratio: 1.1
  friction_time: 700.0
cell:
  size: 2
