
simulations:
  - name: "Basic simulation - 1000 vs 1000"
    cell:
      - type: "Predators"
        n : 1000
      - type: "Prey"
        n : 1000
  - name: "Basic simulation - 500 vs 500"
    cell:
      - type: "Predators"
        n : 500
      - type: "Prey"
        n : 500
  - name: "1vs1"
    cell:
      - type: "Predators"
        n : 1
        from_pos : [10,10]
        to_pos : [11,11]
      - type : "Prey"
        n : 1
        from_pos : [30,30]
        to_pos : [31,31]

